"""Add identity and consent schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 21:52:36.556200

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "consents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("declined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'accepted' AND accepted_at IS NOT NULL AND declined_at IS NULL AND revoked_at IS NULL) OR (status = 'declined' AND accepted_at IS NULL AND declined_at IS NOT NULL AND revoked_at IS NULL) OR (status = 'revoked' AND accepted_at IS NOT NULL AND declined_at IS NULL AND revoked_at IS NOT NULL AND revoked_at >= accepted_at)",
            name=op.f("ck_consents_lifecycle"),
        ),
        sa.CheckConstraint(
            "policy_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'",
            name=op.f("ck_consents_policy_version"),
        ),
        sa.CheckConstraint("length(trim(channel)) > 0", name=op.f("ck_consents_channel_nonempty")),
        sa.CheckConstraint("revision > 0", name=op.f("ck_consents_positive_revision")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_consents_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
        sa.UniqueConstraint("user_id", "revision", name=op.f("uq_consents_user_id")),
    )
    op.create_table(
        "social_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_user_id", sa.String(length=128), nullable=False),
        sa.Column("provider_chat_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(provider)) > 0", name=op.f("ck_social_identities_provider_nonempty")
        ),
        sa.CheckConstraint(
            "length(trim(provider_chat_id)) > 0",
            name=op.f("ck_social_identities_provider_chat_nonempty"),
        ),
        sa.CheckConstraint(
            "length(trim(provider_user_id)) > 0",
            name=op.f("ck_social_identities_provider_user_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_social_identities_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_identities")),
        sa.UniqueConstraint(
            "provider", "provider_user_id", name="uq_social_identities_provider_user"
        ),
    )
    op.create_index(
        op.f("ix_social_identities_user_id"), "social_identities", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_social_identities_user_id"), table_name="social_identities")
    op.drop_table("social_identities")
    op.drop_table("consents")
    op.drop_table("users")
    # ### end Alembic commands ###
