"""Add encrypted birth profiles

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-27 22:54:05.033730

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "birth_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("encrypted_payload", sa.LargeBinary(), nullable=False),
        sa.Column("encryption_key_version", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "encryption_key_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'",
            name=op.f("ck_birth_profiles_encryption_key_version"),
        ),
        sa.CheckConstraint(
            "octet_length(encrypted_payload) >= 29",
            name=op.f("ck_birth_profiles_encrypted_envelope"),
        ),
        sa.CheckConstraint(
            "schema_version > 0", name=op.f("ck_birth_profiles_positive_schema_version")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_birth_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_birth_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_birth_profiles_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("birth_profiles")
    # ### end Alembic commands ###
