"""Add encrypted onboarding drafts

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-28 09:39:17.659106

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_drafts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("encrypted_payload", sa.LargeBinary(), nullable=False),
        sa.Column("encryption_key_version", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "encryption_key_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'",
            name=op.f("ck_onboarding_drafts_encryption_key_version"),
        ),
        sa.CheckConstraint(
            "octet_length(encrypted_payload) >= 29",
            name=op.f("ck_onboarding_drafts_encrypted_envelope"),
        ),
        sa.CheckConstraint("schema_version = 1", name=op.f("ck_onboarding_drafts_schema_version")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_onboarding_drafts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_onboarding_drafts")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("onboarding_drafts")
    # ### end Alembic commands ###
