"""Add durable inbound events

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-28 17:26:47.912094

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_update_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("encrypted_input", sa.LargeBinary(), nullable=True),
        sa.Column("encrypted_reply", sa.LargeBinary(), nullable=True),
        sa.Column("encryption_key_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("failure_code", sa.String(length=32), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'ready', 'sent', 'dead')",
            name=op.f("ck_inbound_events_status"),
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= 5", name=op.f("ck_inbound_events_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_inbound_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbound_events")),
        sa.UniqueConstraint(
            "provider", "provider_update_id", name=op.f("uq_inbound_events_provider")
        ),
        sa.UniqueConstraint("sequence", name=op.f("uq_inbound_events_sequence")),
    )
    op.create_index(
        op.f("ix_inbound_events_next_attempt_at"),
        "inbound_events",
        ["next_attempt_at"],
        unique=False,
    )
    op.create_index(op.f("ix_inbound_events_user_id"), "inbound_events", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inbound_events_user_id"), table_name="inbound_events")
    op.drop_index(op.f("ix_inbound_events_next_attempt_at"), table_name="inbound_events")
    op.drop_table("inbound_events")
    # ### end Alembic commands ###
