"""add durable deletion jobs

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-03 23:39:28.012574

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confirmation_token", sa.String(length=32), nullable=True),
        sa.Column("confirmation_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("encrypted_target", sa.LargeBinary(), nullable=True),
        sa.Column("encryption_key_version", sa.String(length=64), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notification_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("failure_code", sa.String(length=32), nullable=True),
        sa.CheckConstraint(
            "status IN ('confirmation', 'requested', 'local_deleted', 'context_deleted', 'redis_deleted', 'completed')",
            name=op.f("ck_deletion_jobs_status"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_deletion_jobs_attempts")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_jobs")),
        sa.UniqueConstraint("user_id", name=op.f("uq_deletion_jobs_user_id")),
    )
    op.create_index(
        op.f("ix_deletion_jobs_next_attempt_at"), "deletion_jobs", ["next_attempt_at"], unique=False
    )
    op.alter_column("inbound_events", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Deleted owners cannot be restored. Dev-only rollback drops their unlinked receipts.
    op.execute("DELETE FROM inbound_events WHERE user_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("inbound_events", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f("ix_deletion_jobs_next_attempt_at"), table_name="deletion_jobs")
    op.drop_table("deletion_jobs")
    # ### end Alembic commands ###
